/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.FileNotFoundException;
import java.net.MalformedURLException;
import java.util.LinkedList;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {
       @Test
    public void testQuoteClass(){
        List<String> sampleTag = new LinkedList<>();
        sampleTag.add("sample tag");
        Quote test = new Quote("Aseel Albanna", "Ramadan Kareem " );
        assertEquals("Quote author should be the same.", "Aseel Albanna", test.getAuthor());
        assertEquals("Quote text should be the same.", "Ramadan Kareem ", test.getText());
    }

    @Test public void testRandomQuote() throws FileNotFoundException {
        String path = "../app/src/test/resources/test.json";
        QuoteReader test = new QuoteReader(path);
        String expected = " “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.\n- Author: Marilyn Monroe";
        assertEquals("Should contain quotes", expected, test.getRandomQuote());
    }
}
