/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.FileNotFoundException;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        String path = "app/src/main/resources/recentquotes.json";
        QuotesRead qReader = new QuotesRead(path);
        System.out.println(qReader.getRandomQuote());
    }
}


